services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: "on-failure"
    ports:
      - "3006:3006"
    env_file:
      - src/.env
    networks:
      - pln-bot-network

networks:
  pln-bot-network:
    external: true


# services:
#   whatsapp:
#     image: aldinokemal2104/go-whatsapp-web-multidevice
#     container_name: whatsapp
#     restart: always
#     ports:
#       - "3000:3000"
#     volumes:
#       - whatsapp:/app/storages
#     environment:
#       - APP_BASIC_AUTH=admin:admin
#       - APP_PORT=3000
#       - APP_DEBUG=false
#       - APP_OS=Chrome
#       - APP_ACCOUNT_VALIDATION=false

# volumes:
#   whatsapp: